version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: user         
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: bandstream       
    volumes:
      - ~/docker_volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge