name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg S3_PUBLIC_URL=https://storage.cloud.band.stream \
            --build-arg BUILD_COMMIT=${{ gitea.sha }} \
            --build-arg BUILD_BRANCH=${{ gitea.ref_name }} \
            --build-arg BUILD_ENV=prod \
            --build-arg BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
            --build-arg BUILD_RUN_ID=${{ gitea.run_id }} \
            -t registry.bandteam.co/bandstream/bandstream-v2:prod \
            .

      - name: Push to registry
        run: |
          docker push registry.bandteam.co/bandstream/bandstream-v2:prod

      - name: Deploy
        run: |
          kubectl --kubeconfig /etc/kubeconfig/ionos.yaml rollout restart deployment/prod-webapp -n prod
          kubectl --kubeconfig /etc/kubeconfig/ionos.yaml rollout status deployment/prod-webapp -n prod --timeout=120s
